/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh tokens using refresh token from cookie */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["UsersController_findCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Delete user (soft delete) */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all sections (tree structure) */
        get: operations["SectionsController_findAll"];
        put?: never;
        /** Create a new section */
        post: operations["SectionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get section by ID */
        get: operations["SectionsController_findOne"];
        put?: never;
        post?: never;
        /** Delete section (soft delete) */
        delete: operations["SectionsController_remove"];
        options?: never;
        head?: never;
        /** Update section */
        patch: operations["SectionsController_update"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Create a new product */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by ID */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        /** Delete product (soft delete) */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /** Update product */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all warehouses */
        get: operations["WarehousesController_findAll"];
        put?: never;
        /** Create a new warehouse */
        post: operations["WarehousesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get warehouses by ID */
        get: operations["WarehousesController_findOne"];
        put?: never;
        post?: never;
        /** Delete warehouse (soft delete) */
        delete: operations["WarehousesController_remove"];
        options?: never;
        head?: never;
        /** Update warehouse */
        patch: operations["WarehousesController_update"];
        trace?: never;
    };
    "/images/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload product image */
        post: operations["ImagesController_uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{id}/main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set image as main */
        patch: operations["ImagesController_setAsMain"];
        trace?: never;
    };
    "/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete image */
        delete: operations["ImagesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add new offer */
        post: operations["OffersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/p/{parentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all offer current product */
        get: operations["OffersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get offer by ID */
        get: operations["OffersController_findOne"];
        put?: never;
        post?: never;
        /** Delete offer (soft delete) */
        delete: operations["OffersController_remove"];
        options?: never;
        head?: never;
        /** Update offer */
        patch: operations["OffersController_update"];
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all currencies current product */
        get: operations["CurrenciesController_findAll"];
        put?: never;
        /** Add new currencies */
        post: operations["CurrenciesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get currencies by ID */
        get: operations["CurrenciesController_findOne"];
        put?: never;
        post?: never;
        /** Delete currencies (soft delete) */
        delete: operations["CurrenciesController_remove"];
        options?: never;
        head?: never;
        /** Update currencies */
        patch: operations["CurrenciesController_update"];
        trace?: never;
    };
    "/barcodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all barcodes */
        get: operations["BarcodesController_findAll"];
        put?: never;
        /** Add new barcode */
        post: operations["BarcodesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/barcodes/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all barcode current product */
        get: operations["BarcodesController_findByProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/barcodes/offer/{offerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all barcode current offer */
        get: operations["BarcodesController_findByOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/barcodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get barcode by ID */
        get: operations["BarcodesController_findOne"];
        put?: never;
        post?: never;
        /** Delete barcode (soft delete) */
        delete: operations["BarcodesController_remove"];
        options?: never;
        head?: never;
        /** Update barcode */
        patch: operations["BarcodesController_update"];
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all currencies current product */
        get: operations["UnitsController_findAll"];
        put?: never;
        /** Add new currencies */
        post: operations["UnitsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get currencies by ID */
        get: operations["UnitsController_findOne"];
        put?: never;
        post?: never;
        /** Delete currencies (soft delete) */
        delete: operations["UnitsController_remove"];
        options?: never;
        head?: never;
        /** Update currencies */
        patch: operations["UnitsController_update"];
        trace?: never;
    };
    "/pricecategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all price category */
        get: operations["PriceCategoriesController_findAll"];
        put?: never;
        /** Add new currencies */
        post: operations["PriceCategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricecategories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get price category by ID */
        get: operations["PriceCategoriesController_findOne"];
        put?: never;
        post?: never;
        /** Delete price category (soft delete) */
        delete: operations["PriceCategoriesController_remove"];
        options?: never;
        head?: never;
        /** Update price category */
        patch: operations["PriceCategoriesController_update"];
        trace?: never;
    };
    "/taxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all taxes */
        get: operations["TaxesController_findAll"];
        put?: never;
        /** Create a new tax */
        post: operations["TaxesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tax by ID */
        get: operations["TaxesController_findOne"];
        put?: never;
        post?: never;
        /** Delete tax (soft delete) */
        delete: operations["TaxesController_remove"];
        options?: never;
        head?: never;
        /** Update Tax */
        patch: operations["TaxesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example john@doe.ru */
            email: string;
            /** @example password123 */
            password: string;
        };
        User: Record<string, never>;
        LoginResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
            /** @example 3600s */
            expires_in: string;
            /**
             * @example {
             *       "id": 1,
             *       "email": "john@doe.ru",
             *       "firstName": "John",
             *       "lastName": "Doe",
             *       "role": {
             *         "id": 1,
             *         "name": "user",
             *         "createdAt": "2026-05-04T11:29:00.797Z",
             *         "updatedAt": "2026-05-04T11:29:00.797Z"
             *       }
             *     }
             */
            user: components["schemas"]["User"];
        };
        RegisterDto: {
            /** @example john@doe.ru */
            email: string;
            /** @example password123 */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example Ivanovich */
            patronymic: string;
        };
        RegisterResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
            /** @example 3600s */
            expires_in: string;
            /**
             * @example {
             *       "id": 1,
             *       "email": "john@doe.ru",
             *       "firstName": "John",
             *       "lastName": "Doe",
             *       "patronymic": "Ivanovich",
             *       "role": {
             *         "id": 1,
             *         "name": "user",
             *         "createdAt": "2026-05-04T11:29:00.799Z",
             *         "updatedAt": "2026-05-04T11:29:00.799Z"
             *       }
             *     }
             */
            user: components["schemas"]["User"];
        };
        CreateUserDto: Record<string, never>;
        UpdateUserDto: Record<string, never>;
        CreateSectionDto: {
            /** @example Category Name */
            name: string;
            /** @example Category description */
            description?: string;
            /** @example Category code */
            code?: string;
            /** @description Parent section ID for nested sections */
            parentId?: string;
        };
        UpdateSectionDto: {
            /** @example Category Name */
            name: string;
            /** @example Category description */
            description?: string;
            /** @example Category code */
            code?: string;
            /** @description Parent section ID for nested sections */
            parentId?: string;
        };
        CreateProductDto: {
            /** @example Product name */
            name: string;
            /** @example Product full name */
            fullName: string;
            /** @example Product code */
            code?: string;
            /** @example Description product */
            description?: string;
            /** @example SKU-001 */
            sku: string;
            /** @example EX-001 */
            xmlCode: string;
            /**
             * @description Category ID
             * @example category-uuid
             */
            sectionId: string;
            /** @default true */
            isActive: boolean;
            /** @description unit id */
            unitId: string;
        };
        UpdateProductDto: {
            /** @example Product name */
            name: string;
            /** @example Product full name */
            fullName: string;
            /** @example Product code */
            code?: string;
            /** @example Description product */
            description?: string;
            /** @example SKU-001 */
            sku: string;
            /** @example EX-001 */
            xmlCode: string;
            /**
             * @description Category ID
             * @example category-uuid
             */
            sectionId: string;
            /** @default true */
            isActive: boolean;
            /** @description unit id */
            unitId: string;
        };
        CreateWarehouseDto: {
            /** @example Base Store */
            name: string;
            /** @example WH-001 */
            code: string;
            /** @example MO, Moscow 20021 */
            address?: string;
            /** @default true */
            isActive: boolean;
        };
        UpdateWarehouseDto: {
            /** @example Base Store */
            name: string;
            /** @example WH-001 */
            code: string;
            /** @example MO, Moscow 20021 */
            address?: string;
            /** @default true */
            isActive: boolean;
        };
        CreateOfferDto: {
            /** @example Offer name */
            name: string;
            /**
             * @description Product ID
             * @example product-uuid
             */
            parentId: string;
            /** @default true */
            isActive: boolean;
            /**
             * @description External offer code
             * @example ext_code_offer
             */
            xmlCode: string;
        };
        UpdateOfferDto: {
            /** @example Offer name */
            name: string;
            /** @default true */
            isActive: boolean;
            /**
             * @description External offer code
             * @example ext_code_offer
             */
            xmlCode: string;
        };
        CreateCurrenciesDto: {
            /** @example rub */
            name: string;
            /** @example RUB */
            code: string;
            /** @default false */
            isBase: boolean;
            /** @example Russian Ruble */
            fullName: string;
            /**
             * @default 1
             * @example 1.000
             */
            rate: number;
            /** @default true */
            isActive: boolean;
        };
        UpdateCurrenciesDto: {
            /** @example rub */
            name: string;
            /** @example RUB */
            code: string;
            /** @default false */
            isBase: boolean;
            /** @example Russian Ruble */
            fullName: string;
            /**
             * @default 1
             * @example 1.000
             */
            rate: number;
            /** @default true */
            isActive: boolean;
        };
        CreateBarcodeDto: {
            /** @example 123456789 */
            barcode: string;
            /** @example EAN13 */
            type: string;
            /** @example askjdjks... */
            productId: string;
            /** @example askjdjks... */
            offerId: string;
            /** @example asdskdak... */
            unitId: string;
            /** @default true */
            isActive: boolean;
            /** @default 1 */
            rate: number;
        };
        UpdateBarcodeDto: {
            /** @example 123456789 */
            barcode: string;
            /** @example EAN13 */
            type: string;
            /** @example askjdjks... */
            productId: string;
            /** @example askjdjks... */
            offerId: string;
            /** @example asdskdak... */
            unitId: string;
            /** @default true */
            isActive: boolean;
            /** @default 1 */
            rate: number;
        };
        CreateUnitDto: {
            /** @example 796 */
            code: string;
            /** @example шт */
            name: string;
            /** @example Штука */
            fullName: string;
        };
        UpdateUnitDto: {
            /** @example 796 */
            code: string;
            /** @example шт */
            name: string;
            /** @example Штука */
            fullName: string;
        };
        CreatePriceCategoryDto: {
            /** @example Porchasing Price */
            name: string;
            /** @example WH-001 */
            code: string;
            /** @default false */
            isPorchasePrice: boolean;
            /** @example asadasd... */
            currenciesId: string;
        };
        UpdatePriceCategoryDto: {
            /** @example Porchasing Price */
            name: string;
            /** @example WH-001 */
            code: string;
            /** @default false */
            isPorchasePrice: boolean;
            /** @example asadasd... */
            currenciesId: string;
        };
        CreateTaxDto: {
            /** @example No Taxes */
            name: string;
            /**
             * @default 0
             * @example 0
             */
            percent: number;
        };
        UpdateTaxDto: {
            /** @example No Taxes */
            name: string;
            /**
             * @default 0
             * @example 0
             */
            percent: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description User logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query: {
                page: number;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return user by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SectionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all sections as tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SectionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSectionDto"];
            };
        };
        responses: {
            /** @description Section created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SectionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return section by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SectionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Section deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SectionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSectionDto"];
            };
        };
        responses: {
            /** @description Section update successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                sectionId?: number;
                search?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Product created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return product by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Product updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WarehousesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all warehouses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WarehousesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWarehouseDto"];
            };
        };
        responses: {
            /** @description Warehouse created succesfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WarehousesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return warehouses by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WarehousesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Warehouse deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WarehousesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWarehouseDto"];
            };
        };
        responses: {
            /** @description Warehouse updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    /** Format: uuid */
                    productId?: string;
                    /** @default false */
                    isMain?: boolean;
                    /** @default 0 */
                    order?: number;
                };
            };
        };
        responses: {
            /** @description Image uploaded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_setAsMain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image set as main */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OffersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOfferDto"];
            };
        };
        responses: {
            /** @description Offer add successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OffersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all offer current product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OffersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return offer by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OffersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offer deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OffersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOfferDto"];
            };
        };
        responses: {
            /** @description Offer updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrenciesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all currencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrenciesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCurrenciesDto"];
            };
        };
        responses: {
            /** @description Currencies add successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrenciesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return currencies by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrenciesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currencies deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrenciesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurrenciesDto"];
            };
        };
        responses: {
            /** @description Currencies updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all barcodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBarcodeDto"];
            };
        };
        responses: {
            /** @description Barcode add successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_findByProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all barcode current product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_findByOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all barcode current offer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return barcode by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Barcode deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BarcodesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBarcodeDto"];
            };
        };
        responses: {
            /** @description Barcode updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all currencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitDto"];
            };
        };
        responses: {
            /** @description Currencies add successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return currencies by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currencies deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitDto"];
            };
        };
        responses: {
            /** @description Currencies updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PriceCategoriesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all price category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PriceCategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePriceCategoryDto"];
            };
        };
        responses: {
            /** @description Price category add successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PriceCategoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return price category by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PriceCategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price category deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PriceCategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePriceCategoryDto"];
            };
        };
        responses: {
            /** @description Price category updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all taxes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaxDto"];
            };
        };
        responses: {
            /** @description Tax created succesfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return tax by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tax deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaxDto"];
            };
        };
        responses: {
            /** @description Tax updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
